### ISSUE TITLE
文字の縮小に<h5>タグを使用している

### ISSUE THREAD

**Issue by takumiio** [ShuheiFujita/practice1#1]
HTMLではタグごとに意味があるため、
原則、タグでデザイン（レイアウト）を組んではいけません。

なので、h5タグで文字を縮小するのではなく、
CSSを利用して文字を縮小してください。

**Comment by takumiio** [comment]
確認しました！
OKです！

**Comment by ShuheiFujita** [comment]
ありがとうございます！ｗ
